### ISSUE TITLE
Automatically open browser tab for authentication

### ISSUE THREAD

**Issue by brenner-tobias** [brenner-tobias/addon-cloudflared#1]
**Is your feature request related to a problem? Please describe.**
When setting up Cloudflared, you have to manually check the logs of the add-on, copy the authentication link and paste it into a browser window.

**Describe the solution you'd like**
It would be easier to automatically open the link in a new browser tab / a mobile browser for the app to make the authentication a more seaming-less experience. 

**Describe alternatives you've considered**
Since this only needs to be done once, the current solution might also be feasible, depending on the effort.

**Additional context**
The URL is generated by running `/opt/cloudflared tunnel login` as an output to the console. This is done in the file `/cloudflared/rootfs/etc/cont-init.d/02_cloudflared-setup.sh`

**Comment by Misiu** [comment]
@brenner-tobias try asking Home Assistant Devs on the Discord. Especially Frenck, because he is the mastermind behind many addons (https://github.com/hassio-addons)
If there is a way, I'm sure the devs will help, if not, I'm sure a feature request can be created and sooner or later this will be possible.
