### ISSUE TITLE
Cloudflare fail to reconnect after internet lost

### ISSUE THREAD

**Issue by krzysiek2788** [brenner-tobias/addon-cloudflared#125]
### The problem

Hi,

I findout that addon has issue with reconnecting back to Cloudflare tunnel if server lost connection. It looks like Add-on is unable to reset tunnel connection automatically, after I restart add-on all is working fine.

### What version of Cloudflared has the issue?

2.0.4

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
additional_hosts: []
external_hostname: xxxxxxxxxx
tunnel_name: xxxxxxxxx
tunnel_token: ''
data_folder: ssl
```

### Anything in the logs that might be useful for us?

```txt
022-07-16T13:12:39Z ERR Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: read tcp 172.30.33.5:48064->198.41.192.47:7844: read: connection reset by peer" connIndex=3 ip=198.41.192.47
2022-07-16T13:12:39Z ERR Serve tunnel error error="TLS handshake with edge error: read tcp 172.30.33.5:48064->198.41.192.47:7844: read: connection reset by peer" connIndex=3 ip=198.41.192.47
2022-07-16T13:12:39Z INF Retrying connection in up to 1s seconds connIndex=3 ip=198.41.192.47
2022-07-16T13:12:39Z ERR Unable to establish connection with Cloudflare edge error="TLS handshake with edge error: read tcp 172.30.33.5:53778->198.41.192.67:7844: read: connection reset by peer" connIndex=1 ip=198.41.192.67
```

### Steps to reproduce the issue

Disconnect internet for some time and Cloudflare add-on couldn't estabilished connection

**Comment by elcajon** [comment]
Thanks for pointing this out. I've experienced the same problem a couple of times during the last weeks (due to ISP outage and router firmware updates...). I have found an (old and) open upstream [issue](https://github.com/cloudflare/cloudflared/issues/306) for this problem.

For now the only quick workaround I can figure out is to increase the `--retries` value to e.g. 20.

A lasting option would be to implement a monitoring service inside the add-on which triggers a restart if the daemon stucks. I guess we could grab the values from the included metrics server.

**Comment by krzysiek2788** [comment]
Maybe you can implement action according to logs it could look like this:
1. If connection failed -> ping google.com
2. ping untill it success then restart add-on

This is just a simple idea :)

**Comment by Beeez** [comment]
Seeing the same issue here

**Comment by elcajon** [comment]
@brenner-tobias How do you think we should proceed? I also had the problem a few times offsite and could only gain access via VPN to restart the add-on. I would suggest using the integrated metrics endpoint to query the health status.

**Comment by brenner-tobias** [comment]
Thanks for pointing me to this again @elcajon. This sucks and I hoped we could avoid any work-around in our add-on since this should be fixed in the tunnel. Though it seems like a lot of people have an issue now, I think we should move forward with implementing a solution by triggering the metrics endpoint.

**Comment by iosoft** [comment]
> Thanks for pointing me to this again @elcajon. This sucks and I hoped we could avoid any work-around in our add-on since this should be fixed in the tunnel. Though it seems like a lot of people have an issue now, I think we should move forward with implementing a solution by triggering the metrics endpoint.

I wrote a small script that runs on auto-start of HA.
It checks if tunnel.json file exists, if not, it restores a copy from last tunnel.json.bkp

**Comment by elcajon** [comment]
> > Thanks for pointing me to this again @elcajon. This sucks and I hoped we could avoid any work-around in our add-on since this should be fixed in the tunnel. Though it seems like a lot of people have an issue now, I think we should move forward with implementing a solution by triggering the metrics endpoint.
> 
> I wrote a small script that runs on auto-start of HA. It checks if tunnel.json file exists, if not, it restores a copy from last tunnel.json.bkp

You are referring to a different problem. This one isnt about the tunnel file. 😄

**Comment by elcajon** [comment]
You can test this functionality by installing cloudflared from the edge repo
