### ISSUE TITLE
Update fails: Internal Server Error ("manifest unknown")

### ISSUE THREAD

**Issue by brenner-tobias** [brenner-tobias/addon-cloudflared#206]
### The problem

Currently, the update does not work for me in the edge-repository:

>Error updating Cloudflared: Can't install ghcr.io/brenner-tobias/cloudflared/aarch64:inf: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=inf&fromImage=ghcr.io%2Fbrenner-tobias%2Fcloudflared%2Faarch64&platform=linux%2Farm64: Internal Server Error ("manifest unknown")

### What version of Cloudflared has the issue?

Edge

### What was the last working version of Cloudflared?

Edge -1

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Try update on edge repo

**Comment by elcajon** [comment]
I had also thought about creating an issue because of this 😄 
I think this is a supervisor error. Locally, the version file under /mnt/data/supervisor/addons/ff6a162/cloudflared looks correct.I have also had similar errors when an edge version starts with 0, which was ignored by the supervisor. If you release a stable release and the edge repository is updated, the error should be gone. Alternatively, we could report the bug upstream.

**Comment by elcajon** [comment]
By the way, I find it interesting that the supervisor is looking for the inf tag for the image. I don't know where that could come from.

**Comment by elcajon** [comment]
I found https://github.com/home-assistant/supervisor/issues/3314 which refers to this open issue https://github.com/hassio-addons/repository-updater/issues/36
