### ISSUE TITLE
2.4 wifi network shuts down after configuring add on

### ISSUE THREAD

**Issue by ptbpa** [brenner-tobias/addon-cloudflared#460]
### The problem

I'm not sure if this was coincidence, but after configuring this add on my 2.4 wifi network went down.

I'm using an ISP router... Not the best for troubleshooting.
Using latest stable Home assistant OS with brand new installation on raspberry pi 4.

Do you have any known similar problems?

Thank you very much!

### What version of Cloudflared has the issue?

4.2.3

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Installed the addon
Configure it
All devices from 2.4 wifi network goes down

**Comment by brenner-tobias** [comment]
Hi. This sounds super strange and I highly doubt that this has anything to do with the add-on.
Is the PI connected via Ethernet or via Wifi? If it is connected via Wifi, I suggest to hard-wire it and deactivate Wifi.

Apart from that, I really cannot think of any reason why Wifi would go down. There might be an issue with your router shutting down the wifi for whatever reason but still keeping the internet going.

I suggest to to an update on the router (if available), and complete resetting it. After that, do another test without the Add-On and with the Add-On running.

I will close this for now since this is most certainly a router issue, but please feel free to re-open if you have new details that this is actually an issue with the add-on.

**Comment by ptbpa** [comment]
Hi thank you very much for your feedback. I just confirmed today that this is not a problem from the addon. Very sorry to take your time.

Guys having the same issue. Raspberry Pi configs with external SSD/USB 3.0 to SATA adapters cause a huge amount of interference to the 2.4ghz network. 

Workaround: separate from router or devices connected to the wifi network

Thank you for your time
