### ISSUE TITLE
Cached Image

### ISSUE THREAD

**Issue by thib5** [brenner-tobias/addon-cloudflared#478]
### The problem

Hi, i just setup cloudflared and i’m pretty happy, no portfoward no certificate renewal every 3 month etc…

Bu i just notice an issue… it’s caching image. I was able to bypass that in a lot of my front end ninterfae but one image caching still remain, when I send mobile notification. I have an image that update it self in my WWW… if i check the image in Visual Studio i see the real image the last one. if i send it by mobile notification i see the image from yesterday

is there a way to fix that ?

### What version of Cloudflared has the issue?

4.2.6

### What was the last working version of Cloudflared?

4.2.6

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

put any image in www folder than put a new image with the same name it will not update if you access it from the url

**Comment by brenner-tobias** [comment]
Hi, I suggest to have a look at Cloudflares Documentation regarding [Caching](https://developers.cloudflare.com/cache/).

The first ideas, that you could try are:

- [Create Page rules](https://developers.cloudflare.com/cache/how-to/edge-browser-cache-ttl/create-page-rules/#cache-everything)
- [Use Cache Rules (beta)](https://developers.cloudflare.com/cache/how-to/cache-rules/)
- Activate Development Mode for your website in Cloudflare

I am closing this since it is not an issue with the add-on, feel free to open a discussion if you want to.
