### ISSUE TITLE
"Remote tunnel add-on setup" tunnels are always started with loglevel=info (perhaps "Local tunnel add-on setup" as well)

### ISSUE THREAD

**Issue by danielbrunt57** [brenner-tobias/addon-cloudflared#607]
### The problem

The configuration option `log_level:` only applies to the add-on itself but I need `--loglevel=debug` applied to the tunnel startup for tunnel troubleshooting and I do not see any way of increasing the logging level.

### What version of Cloudflared has the issue?

5.1.4

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
external_hostname: ***.ca
additional_hosts:
  - hostname: ***.***.ca
    service: http://##.##.##.##:####
tunnel_name: homeassistant
tunnel_token: >-
  <redacted>
log_level: debug
nginx_proxy_manager: false
```
```


### Anything in the logs that might be useful for us?

```txt
[03:15:30] INFO: Using Cloudflare Remote Management Tunnel
[03:15:30] INFO: All add-on configuration options except tunnel_token will be ignored.
[03:15:30] INFO: Connecting Cloudflare Tunnel...
[03:15:30] DEBUG: cloudflared tunnel --no-autoupdate --metrics=0.0.0.0:36500 --loglevel=info run --token=<redacted>
2024-03-05T11:15:30Z INF Starting tunnel tunnelID=<redacted>
2024-03-05T11:15:30Z INF Version 2024.2.1
2024-03-05T11:15:30Z INF GOOS: linux, GOVersion: go1.21.5, GoArch: arm64
2024-03-05T11:15:30Z INF Settings: map[loglevel:info metrics:0.0.0.0:36500 no-autoupdate:true token:*****]
```

### Steps to reproduce the issue

Set `log_level: debug` and observe that remote managed tunnel is slways started with `--loglevel=info`

### Additional information

[Cloudflare Tunnel Run Parameters - ](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/configure-tunnels/tunnel-run-parameters/#logfile)
![image](https://github.com/brenner-tobias/addon-cloudflared/assets/49846893/1fc39b93-756c-42ca-8007-a8918b483b3e)

**Comment by elcajon** [comment]
You are right, the mapping of the add-on log level has been set in the past as shown in the snippet below. Mainly to be able to debug errors in the add-on rather than cloudflared errors. In the meantime, however, the add-on is probably more stable than the tunnel. 😉 

https://github.com/brenner-tobias/addon-cloudflared/blob/d325149d9fc778b85aa59ac1871813c11bf0cebb/cloudflared/rootfs/etc/s6-overlay/scripts/cloudflared-config.sh#L315-L328

I have just had a look at this, an additional `run_parameter` would override the value we have set before. I'll create a PR...
