### ISSUE TITLE
Support Local Network Routing Through Warp Client

### ISSUE THREAD

**Issue by ketilmo** [brenner-tobias/addon-cloudflared#62]
Thanks for creating a great add on! 

**Is your feature request related to a problem? Please describe.**
I’m unable to use the Home Assistant apps through the tunnel when authentication is turned on. I’m able to login through the Cloudflare one time password wall, but the apps doesn’t seem to accept the resulting cookie.

**Describe the solution you'd like**
A workaround would be to support the Cloudflare Zero Trust companion app, that effectively creates a VPN to your local network from your device. I have this up an running on a stand-alone device in my LAN, and it works great. It would involve adding this lines to the Cloudflare config

```
warp-routing:
  enabled: true
```

Adding a route to your tunnel like this: 

`cloudflared tunnel route ip add 192.168.XX.0/24 tunnelname`

And finally remove your LAN IP subnet in Cloudflare’s Split Tunnels settings.

See https://digaround.cloud/homeassistant-secure-access-with-cloudflare-warp/ for full context.

**Comment by elcajon** [comment]
The problem with Cloudflare Access when logging in with Home Assistant in the companion apps is known. As a workaround, various forums recommend deactivating the Access rule for a short time and enabling again after successful login. After that Cloudflare Access should work with Home Assistant.

However, I have looked at the warp function and think that it can be implemented without much effort. I will create a first PR later to provide the function.

**Comment by brenner-tobias** [comment]
@ketilmo Looking into this, there are three things that come to my mind.

1. For me, using GitHub as an authentication provider is working, using Google is not. So try using GitHub, if this is a viable solution for you.
2. To clarify: Warp routing is just another way of routing traffic to complete subnets and not only single applications. Therefor, it is not really addressing your problem on its own. The set-up was just done in a way to also use WARP auth in your tutorial. Nevertheless, @elcajon is looking into enabling to use Warp routing, since it is a valid option anyways.
3. Having that said, you can also enable the WARP auth for singe applications. I suggest you do that if you do not want to go with GitHub as auth provider. In the policies section of your home assistant application, you can define that the user has to be authenticated using WARP. You could also create a group for that in the Groups section and then just add it.

Let me know if anything in that comment was not clear or if you have any follow-up questions.

**Comment by ketilmo** [comment]
@brenner-tobias @elcajon,

Thank you so much for your feedback and for implementing this feature in no time. I tried the GitHub integration, but it gives me the same error message in the companion app. But the WARP integration works great. Thanks a lot for implementing it, I highly appreciate it. Keep up the great work.

**Comment by ketilmo** [comment]
I fully understand that this is not something you can fix, as the problem is probably related to the HA app implementation. But hopefully, it will work more flawlessly in the app someday. Thanks again for creating a great add-on. It's appreciated!
