### ISSUE TITLE
HA iOS app not working mobile data

### ISSUE THREAD

**Issue by fhenrique12** [brenner-tobias/addon-cloudflared#717]
### The problem

After the latest update of cloudflared, the HA app can no longer connect when on 3G/4G/5G (mobile data). Before the update it worked perfectly. I noticed that the WebSocket status is set to “Connecting”. On the home page, the error “A server with the specified hostname could not be found. NSURLErrorDomain -1003”. Safari browser, on the same iPhone, I can access the URL normally, even on 3G/4G/5G (mobile data).

### What version of Cloudflared has the issue?

5.1.21

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

not apply

**Comment by brenner-tobias** [comment]
Our latest update was only a dependency update and did not touch the Cloudflared demon. If you have connectivity issues, please restart HA and all your apps and check again. If the problems still occur, please post your add-on logs after trying to connect.

**Comment by kubayz** [comment]
Hi, I'm experiencing the same issue. After updating to version 5.1.21, I am no longer able to access the domain over mobile data. However, when I use a VPN with mobile data, it works fine. When connected to an external Wi-Fi network, everything functions as expected, so the problem seems to be limited to mobile data. I have already tried restarting the device. Below is the error from the addon log:
`ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp 172.30.32.1:8123: connect: connection refused" connIndex=0 dest=http://myhomeassistantdomain.site/api/websocket event=0 ip=198.41.200.53 type=ws`
