### ISSUE TITLE
Image in documentation for remote tunnel misleading(?)

### ISSUE THREAD

**Issue by d95andek** [brenner-tobias/addon-cloudflared#720]
### The problem

I followed this image in the instructions for configuring remote tunnel exactly:
![image](https://github.com/user-attachments/assets/2a9684cc-79fd-4ee6-9d95-4fc70612114e)
(Especially due to the text: All other configuration options will be ignored.)

The tunnel started just fine, but I was unable to connect to Home Assistant.

After quite some time I tried to add the hostname in "External Homeasstant Hostname" (that I initially kept empty) and then after a restart of the Add-On I was able to connect.

I don't know why that helped or when that is necessary, but perhaps the image in the instructions should be updated (if the External Homeasstant Hostname is necessary always). Or some text should be added (if it is necessary in some cases).

### What version of Cloudflared has the issue?

5.1.22

### What type of installation are you running?

Home Assistant OS

### Steps to reproduce the issue

Don't enter anything in External Homeasstant Hostname.

**Comment by brenner-tobias** [comment]
Thanks for raisining this. I do not believe the documentation is misleading, since it behaves like described: If you enter the tunnel_token, all other options are ignored. By doing that, you are telling the addon that you configured the tunnel in the cloudflared zero trust dashboard, so nothing else can be done locally.
If you did add the tunnel name, this might be a coincident that it started working. Please try to remove it again and check if it is still working. If not, please post the full logs so I can have a look.

**Comment by d95andek** [comment]
How strange! I removed the hostname and it still worked.
When I added the tunnel I tried again and again to get it to work. And the only thing I really(?) did change in the end was adding the hostname. But there must have been something else.

Sorry for bothering you! And thank you for your clever answer.
