### ISSUE TITLE
400: Bad request.

### ISSUE THREAD

**Issue by DragonsRule10** [brenner-tobias/addon-cloudflared#745]
### The problem

Won't let me access the HA web server, I've tried from both the add-on and another device on the network.

### What version of Cloudflared has the issue?

5.2.2

### What type of installation are you running?

Home Assistant OS

### Add-on YAML Configuration

```yaml
No addon.
```

### Anything in the logs that might be useful for us?

```txt
From home assistant:
Logger: homeassistant.components.http.forwarded
Source: components/http/forwarded.py:97
integration: HTTP (documentation, issues)
First occurred: December 1, 2024 at 8:52:25 AM (40 occurrences)
Last logged: 5:35:42 PM

A request from a reverse proxy was received from 192.168.0.17, but your HTTP integration is not set-up for reverse proxies
A request from a reverse proxy was received from 172.30.33.2, but your HTTP integration is not set-up for reverse proxies

From Add-on:
2024-12-05T23:30:45Z ERR  error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8123: connect: connection refused" connIndex=1 event=1 ingressRule=0 originService=http://localhost:8123
2024-12-05T23:30:45Z ERR Request failed error="Unable to reach the origin service. The service may be down or it may not be responding to traffic from cloudflared: dial tcp [::1]:8123: connect: connection refused" connIndex=1 dest=https://ha.tristinkorbel.xyz/ event=0 ip=198.41.200.113 type=http
```

### Steps to reproduce the issue

By going to ha.tristinkorbel.xyz

### Additional information

None.

**Comment by bamcauliffe** [comment]
This YouTube video shows that you are close, but just have another couple of steps in the process.
YouTube Channel = Everything Smart Home
Video name = The Easiest Free Way To Do Home Assistant Remote Access!
Video link = https://www.youtube.com/watch?v=xXAwT9N-7Hw&t=563s

**Comment by brenner-tobias** [comment]
Did you follow all steps, see [here](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#local-tunnel-add-on-setup-recommended)?
Specifically the [configuration yaml of HomeAssistant](https://github.com/brenner-tobias/addon-cloudflared/blob/main/cloudflared/DOCS.md#configurationyaml) is important, otherwise HA does block the request from Cloudflared and your error suggests that this is missing.

Closing this for now since it feels like a configuration issue on your end. Please start a [discussion](https://github.com/brenner-tobias/addon-cloudflared/discussions) if you have configuration questions or re-open if there is still an general issue to work on for us.
